package com.example.projectbmi

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.selection.selectable
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import com.example.projectbmi.model.DailyQuestParams
import com.example.projectbmi.model.QuestTask
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AskAIScreenClean(
    navController: NavController,
    userBMICategory: String = "normal",
    onSaveSchedule: (schedule: List<QuestTask>) -> Unit
) {
    var state by remember { mutableStateOf(UserDiscoveryState(bmiCategory = userBMICategory)) }
    var generated by remember { mutableStateOf<List<QuestTask>?>(null) }
    val scope = rememberCoroutineScope()

    Scaffold(topBar = {
        TopAppBar(title = { Text("Ask AI / Discovery") }, navigationIcon = {
            IconButton(onClick = { navController.popBackStack() }) { Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back") }
        })
    }) { paddingValues ->
        Column(modifier = Modifier.fillMaxSize().padding(paddingValues).padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            LinearProgressIndicator(progress = (state.currentStep - 1) / 6f, modifier = Modifier.fillMaxWidth())

            Box(modifier = Modifier.weight(1f)) {
                when {
                    generated != null -> PreviewAndSave(schedule = generated!!, onSave = {
                        onSaveSchedule(generated!!)
                        navController.navigate("dailyquest")
                    })
                    state.currentStep == 1 -> StepPrimaryGoal(state, onStateChange = { state = it })
                    state.currentStep == 2 -> StepExerciseFrequency(state, onStateChange = { state = it })
                    state.currentStep == 3 -> StepEatingPattern(state, onStateChange = { state = it })
                    state.currentStep == 4 -> StepSleepHours(state, onStateChange = { state = it })
                    state.currentStep == 5 -> StepChallenges(state, onStateChange = { state = it })
                    state.currentStep == 6 -> SummaryStep(state = state, isLoading = state.isLoading, onGenerate = {
                        state = state.copy(isLoading = true)
                        scope.launch {
                            try {
                                val params = DailyQuestParams(
                                    bmiCategory = state.bmiCategory,
                                    goal = state.primaryGoal ?: "maintain",
                                    intensity = mapFrequencyToIntensity(state.exerciseFrequency),
                                    timeAvailable = 30,
                                    focusArea = state.eatingPattern ?: "balanced",
                                    healthStatus = "healthy",
                                    exerciseHistory = mapExerciseFrequencyToHistory(state.exerciseFrequency),
                                    dietaryPreference = "omnivore"
                                )
                                generated = com.example.projectbmi.AIRepository.generateWeeklySchedule(params)
                            } catch (e: Exception) {
                                generated = emptyList()
                            }
                            state = state.copy(isLoading = false)
                        }
                    }, onBack = { state = state.copy(currentStep = 5) })
                }
            }

            if (generated == null) {
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    if (state.currentStep > 1) Button(onClick = { state = state.copy(currentStep = state.currentStep - 1) }, modifier = Modifier.weight(1f)) { Text("Back") }
                    val answered = when (state.currentStep) {
                        1 -> state.primaryGoal != null
                        2 -> state.exerciseFrequency != null
                        3 -> state.eatingPattern != null
                        4 -> state.sleepHours != null
                        5 -> state.challenges.isNotEmpty()
                        else -> true
                    }
                    Button(onClick = { state = state.copy(currentStep = state.currentStep + 1) }, enabled = answered, modifier = Modifier.weight(1f)) { Text("Next") }
                }
            }
        }
    }
}

// Reuse small helper components from AskAIScreen; keep names unique here to avoid collisions if old file remains.
@Composable
fun StepPrimaryGoal(state: UserDiscoveryState, onStateChange: (UserDiscoveryState) -> Unit) {
    val options = listOf("Lose weight" to "weight-loss", "Gain weight" to "gain", "Maintain ideal weight" to "maintain", "Check BMI status" to "check")
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        options.forEach { (label, value) ->
            Row(modifier = Modifier.fillMaxWidth().selectable(selected = state.primaryGoal == value, onClick = { onStateChange(state.copy(primaryGoal = value)) }).padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                RadioButton(selected = state.primaryGoal == value, onClick = { onStateChange(state.copy(primaryGoal = value)) })
                Spacer(modifier = Modifier.width(12.dp))
                Text(label)
            }
        }
    }
}

@Composable
fun StepExerciseFrequency(state: UserDiscoveryState, onStateChange: (UserDiscoveryState) -> Unit) {
    val options = listOf("Never" to "never", "1 - 2 times" to "one-two", "3 - 5 times" to "three-five", "Daily" to "daily")
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        options.forEach { (label, value) ->
            Row(modifier = Modifier.fillMaxWidth().selectable(selected = state.exerciseFrequency == value, onClick = { onStateChange(state.copy(exerciseFrequency = value)) }).padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                RadioButton(selected = state.exerciseFrequency == value, onClick = { onStateChange(state.copy(exerciseFrequency = value)) })
                Spacer(modifier = Modifier.width(12.dp))
                Text(label)
            }
        }
    }
}

@Composable
fun StepEatingPattern(state: UserDiscoveryState, onStateChange: (UserDiscoveryState) -> Unit) {
    val options = listOf("Irregular" to "irregular", "Overeating" to "overeating", "Balanced" to "balanced", "Specific diet" to "specific")
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        options.forEach { (label, value) ->
            Row(modifier = Modifier.fillMaxWidth().selectable(selected = state.eatingPattern == value, onClick = { onStateChange(state.copy(eatingPattern = value)) }).padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                RadioButton(selected = state.eatingPattern == value, onClick = { onStateChange(state.copy(eatingPattern = value)) })
                Spacer(modifier = Modifier.width(12.dp))
                Text(label)
            }
        }
    }
}

@Composable
fun StepSleepHours(state: UserDiscoveryState, onStateChange: (UserDiscoveryState) -> Unit) {
    val options = listOf("< 5 hours" to "less-5", "5-7" to "5-7", "7-9" to "7-9", "> 9" to "more-9")
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        options.forEach { (label, value) ->
            Row(modifier = Modifier.fillMaxWidth().selectable(selected = state.sleepHours == value, onClick = { onStateChange(state.copy(sleepHours = value)) }).padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                RadioButton(selected = state.sleepHours == value, onClick = { onStateChange(state.copy(sleepHours = value)) })
                Spacer(modifier = Modifier.width(12.dp))
                Text(label)
            }
        }
    }
}

@Composable
fun StepChallenges(state: UserDiscoveryState, onStateChange: (UserDiscoveryState) -> Unit) {
    val options = listOf("Finding time", "Diet pattern", "Lack of motivation", "Busy schedule", "Other")
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        options.forEach { label ->
            Row(modifier = Modifier.fillMaxWidth().clickable {
                val new = if (state.challenges.contains(label)) state.challenges - label else state.challenges + label
                onStateChange(state.copy(challenges = new))
            }.padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                Checkbox(checked = state.challenges.contains(label), onCheckedChange = { checked ->
                    val new = if (checked) state.challenges + label else state.challenges - label
                    onStateChange(state.copy(challenges = new))
                })
                Spacer(modifier = Modifier.width(12.dp))
                Text(label)
            }
        }
    }
}

@Composable
fun SummaryStep(state: UserDiscoveryState, isLoading: Boolean, onGenerate: () -> Unit, onBack: () -> Unit) {
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        Text("Summary", style = MaterialTheme.typography.headlineSmall)
        Card(modifier = Modifier.fillMaxWidth()) {
            Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                SummaryRow("Goal", state.primaryGoal ?: "—")
                Divider()
                SummaryRow("Exercise", state.exerciseFrequency ?: "—")
                Divider()
                SummaryRow("Eating", state.eatingPattern ?: "—")
                Divider()
                SummaryRow("Sleep", state.sleepHours ?: "—")
                Divider()
                SummaryRow("Challenges", state.challenges.joinToString(", "))
            }
        }
        Button(onClick = onGenerate, modifier = Modifier.fillMaxWidth(), enabled = !isLoading) { Text("Generate") }
        OutlinedButton(onClick = onBack, modifier = Modifier.fillMaxWidth()) { Text("Back") }
    }
}

@Composable
fun PreviewAndSave(schedule: List<QuestTask>, onSave: () -> Unit) {
    Column(modifier = Modifier.fillMaxSize(), verticalArrangement = Arrangement.spacedBy(12.dp)) {
        Text("Preview Schedule", style = MaterialTheme.typography.headlineSmall)
        LazyColumn(modifier = Modifier.weight(1f)) { items(schedule) { t -> Card(modifier = Modifier.fillMaxWidth().padding(6.dp)) { Column(modifier = Modifier.padding(8.dp)) { Text(t.day, fontWeight = FontWeight.Bold); Spacer(modifier = Modifier.height(4.dp)); Text(t.task) } } } }
        Button(onClick = onSave, modifier = Modifier.fillMaxWidth()) { Text("Save") }
    }
}

@Composable
fun SummaryRow(label: String, value: String) {
    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Text(label)
        Text(value, fontWeight = FontWeight.Bold)
    }
}

fun mapFrequencyToIntensity(freq: String?): String = when (freq) {
    "never" -> "low"
    "one-two" -> "low"
    "three-five" -> "medium"
    "daily" -> "high"
    else -> "medium"
}

fun mapExerciseFrequencyToHistory(freq: String?): String = when (freq) {
    "never" -> "beginner"
    "one-two" -> "inconsistent"
    "three-five" -> "active"
    "daily" -> "active"
    else -> "beginner"
}

// lightweight local state type shared with this file
data class UserDiscoveryState(
    val bmiCategory: String = "normal",
    val primaryGoal: String? = null,
    val exerciseFrequency: String? = null,
    val eatingPattern: String? = null,
    val sleepHours: String? = null,
    val challenges: List<String> = emptyList(),
    val currentStep: Int = 1,
    val isLoading: Boolean = false
)
